import supabase from '../lib/supabase.js';
import { Resend } from 'resend';

const log = (msg) => console.log(`[${new Date().toISOString()}] [WeeklyScrum] ${msg}`);

export default async function processWeeklyScrum(_job) {
  log('Starting weekly scrum email job');

  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_API_KEY) {
    log('RESEND_API_KEY not configured — skipping');
    return { skipped: true };
  }

  const resend = new Resend(RESEND_API_KEY);
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'datalab@sparksgroup.com';
  const fromName = process.env.RESEND_FROM_NAME || 'SPARKS DataLab';

  // Gather stats
  const { data: requests } = await supabase
    .from('requests')
    .select('id, title, status, priority, company, created_at')
    .order('created_at', { ascending: false })
    .limit(20);

  const { count: totalRequests } = await supabase
    .from('requests')
    .select('*', { count: 'exact', head: true });

  const { count: inProgress } = await supabase
    .from('requests')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'In Progress');

  const { count: completed } = await supabase
    .from('requests')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'Completed');

  const { count: totalDatasets } = await supabase
    .from('datasets')
    .select('*', { count: 'exact', head: true });

  const { count: totalContacts } = await supabase
    .from('contacts')
    .select('*', { count: 'exact', head: true });

  // Get all active users
  const { data: users } = await supabase
    .from('users')
    .select('email')
    .eq('is_active', true);

  const emails = (users || []).map((u) => u.email).filter(Boolean);
  if (emails.length === 0) {
    log('No active users with email — skipping');
    return { skipped: true };
  }

  const escapeHtml = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const recentRows = (requests || [])
    .slice(0, 10)
    .map((r) => `<tr><td style="padding:6px 10px;border-bottom:1px solid #eee">${escapeHtml(r.title)}</td><td style="padding:6px 10px;border-bottom:1px solid #eee">${escapeHtml(r.status)}</td><td style="padding:6px 10px;border-bottom:1px solid #eee">${escapeHtml(r.company)}</td></tr>`)
    .join('');

  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  const { data, error } = await resend.emails.send({
    from: `${fromName} <${fromEmail}>`,
    to: emails,
    subject: `Weekly Scrum Report — ${dateStr}`,
    html: `
      <div style="font-family:sans-serif;max-width:640px;margin:0 auto">
        <h2 style="color:#4338ca">SPARKS DataLab — Weekly Report</h2>
        <p style="color:#666">Week ending ${dateStr}</p>
        <table style="width:100%;border-collapse:collapse;margin:20px 0">
          <tr><td style="padding:8px;color:#666">Total Requests</td><td style="padding:8px;font-weight:700">${totalRequests || 0}</td></tr>
          <tr><td style="padding:8px;color:#666">In Progress</td><td style="padding:8px;font-weight:700;color:#d97706">${inProgress || 0}</td></tr>
          <tr><td style="padding:8px;color:#666">Completed</td><td style="padding:8px;font-weight:700;color:#059669">${completed || 0}</td></tr>
          <tr><td style="padding:8px;color:#666">Datasets</td><td style="padding:8px;font-weight:700">${totalDatasets || 0}</td></tr>
          <tr><td style="padding:8px;color:#666">Contacts</td><td style="padding:8px;font-weight:700">${totalContacts || 0}</td></tr>
        </table>
        ${recentRows ? `
        <h3 style="color:#374151">Recent Requests</h3>
        <table style="width:100%;border-collapse:collapse">
          <thead><tr style="background:#f3f4f6"><th style="text-align:left;padding:8px 10px">Title</th><th style="text-align:left;padding:8px 10px">Status</th><th style="text-align:left;padding:8px 10px">Company</th></tr></thead>
          <tbody>${recentRows}</tbody>
        </table>` : ''}
        <p style="margin-top:24px;font-size:12px;color:#9ca3af">Generated by SPARKS DataLab workers on ${new Date().toISOString()}</p>
      </div>
    `,
  });

  if (error) {
    log(`Resend error: ${error.message}`);
    throw new Error(error.message);
  }

  log(`Weekly scrum sent to ${emails.length} users, id=${data?.id}`);
  return { sent: emails.length, id: data?.id };
}
