import { Resend } from 'resend';

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'datalab@sparksgroup.com';
const FROM_NAME = process.env.RESEND_FROM_NAME || 'SPARKS DataLab';

const log = (msg) => console.log(`[${new Date().toISOString()}] [Resend] ${msg}`);

function getClient() {
  if (!RESEND_API_KEY) throw new Error('RESEND_API_KEY is not configured');
  return new Resend(RESEND_API_KEY);
}

export async function sendAssignmentEmail(toUsers, request) {
  const resend = getClient();
  const emails = toUsers.map((u) => u.email).filter(Boolean);
  if (emails.length === 0) {
    log('sendAssignmentEmail: no recipient emails');
    return;
  }

  log(`sendAssignmentEmail: to=${emails.join(', ')}, request="${request.title}"`);

  const { data, error } = await resend.emails.send({
    from: `${FROM_NAME} <${FROM_EMAIL}>`,
    to: emails,
    subject: `New Assignment: ${request.title}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #4338ca;">New Request Assigned to You</h2>
        <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
          <tr><td style="padding: 8px; color: #666;">Title</td><td style="padding: 8px; font-weight: 600;">${escapeHtml(request.title)}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Company</td><td style="padding: 8px;">${escapeHtml(request.company || 'N/A')}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Priority</td><td style="padding: 8px;">${escapeHtml(request.priority || 'Normal')}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Market</td><td style="padding: 8px;">${escapeHtml(request.market || 'N/A')}</td></tr>
        </table>
        <p>${escapeHtml(request.requirement || '')}</p>
        <p style="margin-top: 24px;">
          <a href="${process.env.CLIENT_URL || 'http://localhost:5173'}/requests/${request.id}" 
             style="background: #4338ca; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none;">
            View Request
          </a>
        </p>
      </div>
    `,
  });

  if (error) {
    log(`sendAssignmentEmail error: ${error.message}`);
    throw new Error(error.message);
  }
  log(`sendAssignmentEmail: sent id=${data?.id}`);
  return data;
}

export async function sendWeeklyScrumEmail(allUsers, reportData) {
  const resend = getClient();
  const emails = allUsers.map((u) => u.email).filter(Boolean);
  if (emails.length === 0) {
    log('sendWeeklyScrumEmail: no recipients');
    return;
  }

  log(`sendWeeklyScrumEmail: to ${emails.length} users`);

  const statsRows = Object.entries(reportData.stats || {})
    .map(([k, v]) => `<tr><td style="padding: 6px 12px; color: #666;">${escapeHtml(k.replace(/_/g, ' '))}</td><td style="padding: 6px 12px; font-weight: 600;">${v}</td></tr>`)
    .join('');

  const recentList = (reportData.recent || [])
    .slice(0, 10)
    .map((r) => `<li>${escapeHtml(r.title)} — <strong>${escapeHtml(r.status)}</strong></li>`)
    .join('');

  const { data, error } = await resend.emails.send({
    from: `${FROM_NAME} <${FROM_EMAIL}>`,
    to: emails,
    subject: `Weekly Scrum Report — ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #4338ca;">Weekly Scrum Report</h2>
        <h3>Summary</h3>
        <table style="border-collapse: collapse; margin: 12px 0;">${statsRows}</table>
        ${recentList ? `<h3>Recent Requests</h3><ul>${recentList}</ul>` : ''}
        <p style="margin-top: 24px; color: #999; font-size: 12px;">
          Generated by SPARKS DataLab on ${new Date().toISOString()}
        </p>
      </div>
    `,
  });

  if (error) {
    log(`sendWeeklyScrumEmail error: ${error.message}`);
    throw new Error(error.message);
  }
  log(`sendWeeklyScrumEmail: sent id=${data?.id}`);
  return data;
}

export async function sendOverdueAlert(users, request) {
  const resend = getClient();
  const emails = users.map((u) => u.email).filter(Boolean);
  if (emails.length === 0) {
    log('sendOverdueAlert: no recipients');
    return;
  }

  log(`sendOverdueAlert: request="${request.title}", to=${emails.join(', ')}`);

  const { data, error } = await resend.emails.send({
    from: `${FROM_NAME} <${FROM_EMAIL}>`,
    to: emails,
    subject: `⚠️ Overdue: ${request.title}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #dc2626;">Overdue Request Alert</h2>
        <p>The following request is past its due date and requires attention:</p>
        <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
          <tr><td style="padding: 8px; color: #666;">Title</td><td style="padding: 8px; font-weight: 600;">${escapeHtml(request.title)}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Due Date</td><td style="padding: 8px; color: #dc2626; font-weight: 600;">${escapeHtml(request.due_date || 'Not set')}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Status</td><td style="padding: 8px;">${escapeHtml(request.status || 'Unknown')}</td></tr>
          <tr><td style="padding: 8px; color: #666;">Priority</td><td style="padding: 8px;">${escapeHtml(request.priority || 'Normal')}</td></tr>
        </table>
        <p style="margin-top: 24px;">
          <a href="${process.env.CLIENT_URL || 'http://localhost:5173'}/requests/${request.id}" 
             style="background: #dc2626; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none;">
            View Request
          </a>
        </p>
      </div>
    `,
  });

  if (error) {
    log(`sendOverdueAlert error: ${error.message}`);
    throw new Error(error.message);
  }
  log(`sendOverdueAlert: sent id=${data?.id}`);
  return data;
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
